"""Generate expected reference signals from the Python strategies.

Output:
- python/delta_bt/tests/fixtures/expected_signals.json
- tests/strategies/fixtures/expected_signals.json

Both test suites load this file so the parity suite stays in sync.
"""
from __future__ import annotations

import json
from pathlib import Path

import sys

# Ensure python/delta_bt is importable
sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from delta_bt.core.registry import load_strategy
from delta_bt.core.types import Bar, Signal

PY_FIX = Path(__file__).resolve().parents[1] / "tests" / "fixtures"
TS_FIX = Path(__file__).resolve().parents[3] / "tests" / "strategies" / "fixtures"

FIXTURES = json.loads((PY_FIX / "bars.json").read_text())

DEFAULTS = {
    "ema_cross": {"fast": 9, "slow": 21},
    "ema3": {"fast": 8, "mid": 13, "slow": 21},
    "rsi_mr": {"period": 14, "oversold": 30, "overbought": 70},
    "macd": {"fast": 12, "slow": 26, "signal": 9},
    "supertrend_mom": {"period": 10, "multiplier": 3.0, "mom_len": 14},
    "supertrend_mom_v2": {"period": 10, "multiplier": 3.0, "roc_len": 14},
    "bollinger": {"period": 20, "stdev": 2.0, "mode": "revert"},
    "vwap": {"band_bps": 20, "mode": "trend"},
    "fvg": {"min_gap_pct": 0.1},
    "price_action_engulfing": {"ema_len": 20},
    "price_action_pinbar": {"ema_len": 20},
    "smc_bos_retest": {"swing_len": 5},
    "smc_choch_bos": {"swing_len": 5},
    "smc_liquidity_sweep": {"swing_len": 5},
    "smc_ob": {"swing_len": 5},
    "smc_ob_fvg": {"swing_len": 5},
    "rsi_divergence": {"rsi_len": 14, "swing_len": 5},
    "macd_divergence": {"fast": 12, "slow": 26, "signal": 9, "swing_len": 5},
    "turtle": {"entry_len": 20, "exit_len": 10},
    "bb_ha_supertrend": {"bb_period": 20, "bb_stdev": 2.0, "st_period": 10, "st_multiplier": 3.0},
}


def _bars(name: str) -> list[Bar]:
    from datetime import datetime

    raw = FIXTURES[name]
    out = []
    for r in raw:
        ts = r["ts"] if isinstance(r["ts"], datetime) else datetime.fromisoformat(r["ts"])
        out.append(Bar(
            ts=ts,
            open=float(r["open"]),
            high=float(r["high"]),
            low=float(r["low"]),
            close=float(r["close"]),
            volume=float(r["volume"]),
            symbol=str(r["symbol"]),
            resolution=str(r["resolution"]),
        ))
    return out



def _last_actionable(signals: list[str]) -> str:
    for s in reversed(signals):
        if s in ("BUY", "SELL", "FLAT"):
            return s
    return "HOLD"


def main() -> None:
    expected: dict[str, dict[str, str]] = {}
    for name, params in DEFAULTS.items():
        expected[name] = {}
        for fixture_name in FIXTURES:
            bars = _bars(fixture_name)
            try:
                strat = load_strategy(name, params)
                strat.on_start()
            except Exception as e:
                expected[name][fixture_name] = f"ERROR:{e}"
                continue
            signals: list[str] = []
            from delta_bt.core.strategy import StrategyContext
            from delta_bt.core.types import Position
            ctx = StrategyContext(Position(symbol="BTCUSD"), 0.0, 0.0)
            for bar in bars:
                sig = strat.on_bar(bar, ctx)
                signals.append(sig.name if isinstance(sig, Signal) else str(sig))

            expected[name][fixture_name] = _last_actionable(signals)
    out = {
        "version": 1,
        "note": "Generated by python/delta_bt/scripts/export_expected.py from the Python strategies",
        "expected": expected,
    }
    for dest in (PY_FIX, TS_FIX):
        dest.mkdir(parents=True, exist_ok=True)
        (dest / "expected_signals.json").write_text(json.dumps(out, indent=2))
    print("Exported expected_signals.json")


if __name__ == "__main__":
    main()
