"""Per-strategy sanity and parity tests.

Each strategy is fed the same shared fixtures the TypeScript side uses, so the
expected signals here are the reference for the TS tests. If Python and TS ever
diverge, the parity CI job will fail first.
"""
from __future__ import annotations

import json
from pathlib import Path

import pytest

from conftest import load_bars_json, run_strategy

HERE = Path(__file__).resolve().parent

def _expected_signals() -> dict:
    """Load expected signals from the shared fixtures JSON.

    ``tests/strategies/fixtures/expected_signals.json`` is the source of truth
    generated by ``scripts/export_expected.py`` from the current Python
    strategies. TS reads the same file so both sides stay in sync.
    """
    root = HERE.parent.parent
    path = root / "tests" / "strategies" / "fixtures" / "expected_signals.json"
    return json.loads(path.read_text())["expected"]


@pytest.fixture(scope="module")
def expected() -> dict:
    return _expected_signals()


def _manifest():
    root = HERE.parent.parent
    return json.loads((root / "strategy_manifest.json").read_text())


def _params_for(name: str) -> dict:
    for s in _manifest()["strategies"]:
        if s["name"] == name:
            return s["defaults"].copy()
    return {}


@pytest.mark.parametrize("name,fixture,expected_signal", [
    (name, fixture, sig)
    for name, cases in _expected_signals().items()
    for fixture, sig in cases.items()
])
def test_strategy_expected_signal(name, fixture, expected_signal):
    bars = load_bars_json(fixture)
    signals = run_strategy(name, _params_for(name), bars)
    # last actionable signal is what the scheduler would see on the last bar
    last = next((s for s in reversed(signals) if s in ("BUY", "SELL", "FLAT")), "HOLD")
    assert last == expected_signal, (
        f"{name} on {fixture}: expected last actionable signal {expected_signal}, got {last}. "
        f"Full signal trace: {signals[-10:]}"
    )


def test_all_strategies_have_manifest_entry():
    from delta_bt.core.registry import discover_strategies
    manifest = _manifest()
    registered = {s["name"] for s in manifest["strategies"]}
    discovered = set(discover_strategies().keys())
    missing = discovered - registered
    assert not missing, f"Discovered strategies missing from manifest: {sorted(missing)}"


def test_manifest_matches_python_regime():
    from delta_bt.core.registry import discover_strategies
    manifest = _manifest()
    strategies = discover_strategies()
    for entry in manifest["strategies"]:
        cls = strategies[entry["name"]]
        actual_regime = getattr(cls, "regime", "any")
        assert actual_regime == entry["regime"], (
            f"{entry['name']}: manifest regime {entry['regime']} != Python regime {actual_regime}"
        )
